version: '3.8'

networks:
  chat-network: 
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
    networks:
      - chat-network
  chat-service:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
      - 8080:8080
      networks:
      - chat-network